/**
 * The IPC bridge the screenshot harness swaps in for src/preload/index.ts.
 *
 * The panel is driven entirely through `window.poe2Overlay` — `load()` at the bottom of
 * src/renderer/index.ts asks it for the status and the items and paints from the answers — so
 * standing in a stub with a fixed scene is enough to make the real renderer draw a real panel with
 * no game, no main process and no network. That is why the shots can be regenerated by anyone.
 *
 * Loaded with `contextIsolation: false`, which is what lets these assignments land on the page's own
 * window. The app's preload is untouched and still goes through `contextBridge`; nothing here ships.
 */
const { NOW, ITEMS, STATUS, EDITOR_ROWS, SETUP_STATE, SETTINGS_STATE } = require("./screenshot-data");

/**
 * Every relative time on screen — the rows' "4m ago", the header's price age, the rate-limit
 * countdown — is measured against `Date.now()`. Pinning it to the scene's own clock is what makes
 * the labels stable across runs instead of ageing by however long the harness took to start.
 */
Date.now = () => NOW;

window.poe2Overlay = {
  // The harness pushes nothing, so the three subscriptions are accepted and dropped.
  onPricedItem: () => {},
  onOverlayStatus: () => {},
  onPricingStatus: () => {},
  getStatus: () => Promise.resolve(STATUS),
  getAllItems: () => Promise.resolve(ITEMS),
  clearHistory: () => Promise.resolve(),
  getEditorRows: () => Promise.resolve(EDITOR_ROWS),
  // The mutators are never pressed while a shot is being taken; they resolve rather than throw so a
  // stray click during a manual debugging run can't leave an unhandled rejection in the console.
  repriceItem: () =>
    Promise.resolve({
      item: null,
      reason: null,
      listings: 0,
      matches: 0,
      matchedMods: 0,
      totalMods: 0,
      defencesDropped: false,
      pseudoDropped: false,
      pseudoStats: [],
      mapDropped: false,
      rateLimited: false
    }),
  openTradeSearch: () => Promise.resolve(true),
  openReleasesPage: () => Promise.resolve(true),
  setManualPrice: () => Promise.resolve({ item: null }),
  refreshPrices: () => Promise.resolve({ refreshedAt: NOW, updated: true }),
  cancelPricing: () => Promise.resolve(true)
};

window.poe2Setup = {
  getConfig: () => Promise.resolve(SETUP_STATE),
  save: () => Promise.resolve()
};

window.poe2Settings = {
  getConfig: () => Promise.resolve(SETTINGS_STATE),
  save: () => Promise.resolve({ invalid: [], refused: [] })
};
